# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SaitoWallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SaitoWallet
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'SaitoWallet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SaitoWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
